language: go

go:
  - tip

before_install:
  - apt-get install -y wget
  - wget http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
  - apt-key add mosquitto-repo.gpg.key
  - apt-get update
  - apt-get install -y mosquitto
  